### ISSUE TITLE
Question about map

### ISSUE THREAD

**Issue by albanv** [lirantal/express-version-route#1]
Hi,
First of all, thanks for providing this package :)
I was asking myself why do you use `Map` instead of a _basic_ `Object` ?

**Comment by lirantal** [comment]
Happy you like it, and thanks for chiming in!

I agree it could be argued that the same could have been done with object notation, although objects tend lend themselves through-out the code and we could have accidentally walked over object properties which aren't really the versions definitions. 

Would be happy to hear more feedback, and better yet a PR :-)

**Comment by albanv** [comment]
In fact, I was thinking about old node versions which don't have a `Map` type built-in.
And since your code is very clean and simple compared to other library mentionned in readme, it will be more straightforward to use the type used by the vast majority of developers, same if use the better tool available is a reasoning quite valid.

If it's ok for you, I'll be glad to submit a PR :)

**Comment by lirantal** [comment]
I'm not totally convinced I want to change the API to object notations yet. I think old node versions isn't a strong argument because v4 is on maintenance mode and the v6.10 should be mainstream. Regardless, v4 does support maps: http://node.green
