### ISSUE TITLE
feature request: unsatisfiable version should call next with error

### ISSUE THREAD

**Issue by trycatchal** [lirantal/express-version-route#29]
Hi.

Clean package :).

I'd like to request that the case that there's no matched version calls next with a specific error.  My justification is that it allows much easier retirement of old versions when you no longer want to support them - and it can all be done in one place.

The only workaround with the current implementation is to do it in a 'default', but you still have to scatter it throughout every route configuration.

Thanks!

**Comment by lirantal** [comment]
Hi @captaincaius, thanks! ❤️

I agree and think that's a good idea!
Would you like to open a PR that adds this?

**Comment by trycatchal** [comment]
Awesome!

Sure - I'll try to fork it today and submit the PR.

Thanks for your openness!

**Comment by trycatchal** [comment]
Hi.

LMK if the exports change is a showstopper or not.  If it is, I can rewrite it so it's the same as it is now.  If not, I'll need to update the doc in the PR too.

Thanks again!

**Comment by lirantal** [comment]
Apologies on the delay @captaincaius. I've been traveling lately and getting back now on track with things. Let's further discuss in the PR.

**Comment by trycatchal** [comment]
No need to apologize.  Thanks for taking the time to review! :)

I'll be traveling too, but I'll try to address your requests hopefully this weekend.

**Comment by lirantal** [comment]
Make sure to rest too ❤️

**Comment by lirantal** [comment]
Introduced by #30
