### ISSUE TITLE
Add support for error objects

### ISSUE THREAD

**Issue by lirantal** [lirantal/express-version-route#36]
In order to use custom error objects instead of relying on their actual name strings we can create an `errors/` directory with the errors on it. Internally in the program we can simply consumer that just like any other import and for external access projects can just require it as well like:

```js
const { CustomError } = require('express-version-route/errors/')
```
where `errors/` folder will have an index.js that will export all error classes

cc @captaincaius

**Comment by trycatchal** [comment]
:+1:

Since there's only one error i'll just leave it in errors/index.js for now unless you want otherwise.

**Comment by trycatchal** [comment]
I'll also pull that static off before someone uses it :P

**Comment by lirantal** [comment]
Haha good idea. Sounds like a plan ;-)
