### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: versionRouter.route is not a function

### ISSUE THREAD

**Issue by arvindgemini** [lirantal/express-version-route#59]
Getting exception error, added sample code only 

import * as versionRouter from 'express-version-route';
import { Router, Handler, Request, Response } from 'express';
const routesMap = new Map<string, Handler>();
const route = Router();

export default (app: Router) => {
  app.use('/version-customer', route);

  routesMap.set('1.0', (req, res, next) => {
    return res.status(200).json({ message: 'hello to you version 1.0' });
  });

  routesMap.set('default', (req, res, next) => {
    return res.status(200).json({ message: 'hello to you, this is the default route' });
  });

  route.get('/test', versionRouter.route(routesMap));
};

**Comment by lirantal** [comment]
I think you're not importing it correctly. 
What if you try the following import?

```
import versionRouter from 'express-version-route';
```

**Comment by arvindgemini** [comment]
Thanks @LiranBri types were missing  which causing the issue.
